### ISSUE TITLE
lib/lib/joins.js does not import collection

### ISSUE THREAD

**Issue by ljack** [perak/kitchen-site#279]
lib/lib/joins.js which is generated when using join collection in collection field does not import the required collection thus causes server to crash. 
```
W20160406-20:16:25.713(0)? (STDERR) ReferenceError: Todos is not defined
W20160406-20:16:25.714(0)? (STDERR)     at meteorInstall.lib.joins.joins.js (lib/joins/joins.js:2:1)
W20160406-20:16:25.714(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:158:9)
W20160406-20:16:25.714(0)? (STDERR)     at require (packages/modules-runtime.js:92:16)
```

``` lib/joins/joins.js
// Todos
Todos.join(Users, "owner.name", "owner", []);
```

**Comment by ljack** [comment]
But maybe we really don't nead joins.js but rather do the joining in transform in queries? transform seems like THE place do prepare the data JSON.
