### ISSUE TITLE
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by yilunyu** [perak/kitchen-site#328]
I want to try the iot example listed on the website. I cloned the git repository and typed this command: "meteor-kitchen ./example-iot.json ./example-iot". It produced the following error:
` npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.` 

The full log is as follows: 

`While loading package perak:mqtt-collection@1.0.4:
error: Command failed:
/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val)
{
^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val)
{
^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
'node'
, node::smalloc::FreeCallback callback
~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to
'New'
return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
^~~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note: candidate
function not viable: no known conversion from 'uint32_t' (aka 'unsigned int')
to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate*
isolate,
^
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note: candidate
function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate*
isolate,
^
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:28:40: note: candidate
function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t
length);
^
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:36:40: note: candidate
function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate*
isolate,
^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:676:12: error: no viable conversion from returned
value of type 'v8::MaybeLocal<v8::Object>' to function return type
'v8::Local<v8::Object>'
return node::Buffer::New(v8::Isolate::GetCurrent(), size);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate
constructor (the implicit copy constructor) not viable: no known conversion
from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st
argument
class Local {
^
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate
constructor (the implicit move constructor) not viable: no known conversion
from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st
argument
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:214:13: note: candidate template
ignored: could not match 'Local' against 'MaybeLocal'
V8_INLINE Local(Local<S> that)
^
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:326:13: note: candidate template
ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
V8_INLINE Local(S* that)
^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
'node::Buffer'
return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Primitive *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
return
NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Boolean *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Function *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Object *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/yilun/.meteor/packages/perak_mqtt-collection/.1.0.4.1hy8jpj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-u0znmg/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 15.4.0
npm ERR! argv
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/yilun/.meteor/packages/perak_mqtt-collection/.1.0.4.1hy8jpj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-u0znmg/npm-debug.log
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val)
{
^
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val)
{
^
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
'node'
, node::smalloc::FreeCallback callback
~~~~~~^
../node_modules/nan/nan.h:672:12: error: no matching function for call to
'New'
return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
^~~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:31:40: note: candidate
function not viable: no known conversion from 'uint32_t' (aka 'unsigned int')
to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate*
isolate,
^
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:43:40: note: candidate
function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate*
isolate,
^
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:28:40: note: candidate
function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t
length);
^
/Users/yilun/.node-gyp/4.4.7/include/node/node_buffer.h:36:40: note: candidate
function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate*
isolate,
^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:676:12: error: no viable conversion from returned
value of type 'v8::MaybeLocal<v8::Object>' to function return type
'v8::Local<v8::Object>'
return node::Buffer::New(v8::Isolate::GetCurrent(), size);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate
constructor (the implicit copy constructor) not viable: no known conversion
from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st
argument
class Local {
^
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:210:7: note: candidate
constructor (the implicit move constructor) not viable: no known conversion
from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st
argument
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:214:13: note: candidate template
ignored: could not match 'Local' against 'MaybeLocal'
V8_INLINE Local(Local<S> that)
^
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:326:13: note: candidate template
ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
V8_INLINE Local(S* that)
^
In file included from ../src/bufferutil.cc:16:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
'node::Buffer'
return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
~~~~~~~~~~~~~~^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Primitive *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
return
NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Boolean *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Function *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
In file included from ../src/bufferutil.cc:7:
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:221:5: error: assigning to
'v8::Object *volatile' from incompatible type 'v8::Value *'
TYPE_CHECK(T, S);
^~~~~~~~~~~~~~~~
/Users/yilun/.node-gyp/4.4.7/include/node/v8.h:180:37: note: expanded from
macro 'TYPE_CHECK'
*(static_cast<T* volatile*>(0)) = static_cast<S*>(0);
\
^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
^
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val)
scope.Escape(_NanEnsureLocal(val))
^
9 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit
(/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:200:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"
gyp ERR! cwd
/Users/yilun/.meteor/packages/perak_mqtt-collection/.1.0.4.1hy8jpj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-u0znmg/node_modules/mqtt/node_modules/websocket-stream/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm ERR! Darwin 15.4.0
npm ERR! argv
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/yilun/.meteor/packages/meteor-tool/.1.4.0-1.6c0nus++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/yilun/.meteor/packages/perak_mqtt-collection/.1.0.4.1hy8jpj++os.osx.x86_64+web.browser+web.cordova/npm/node_modules/.temp-u0znmg/npm-debug.log


                                              
Error executing "meteor add perak:mqtt-collection http email spiderable ejson random iron:router fortawesome:fontawesome matb33:collection-hooks copleykj:livestamp less nemo64:bootstrap@=3.3.5_2 reactive-dict mizzao:bootboxjs". Error executing "meteor". No such file or directory`

I am running node v4.4.7 and npm 3.10.5

**Comment by perak** [comment]
Hi @yilunyu pkease see this issue: https://github.com/perak/meteor-mqtt-collection/issues/7

**Comment by perak** [comment]
I'l try to fix this today in next few hours

**Comment by perak** [comment]
@yilunyu OK, fixed. `perak:mqtt-collection@1.0.5`

**Comment by perak** [comment]
Just build application again (clean build into new directory)

**Comment by yilunyu** [comment]
Yay it's working!! Thank you very much. awesome project btw i love it!!! is there a way to combine meteor with a mosquitto broker? I want to use the MQTT protocol on the client side and i don't know how to handle it with server side meteor.

**Comment by perak** [comment]
@yilunyu Sorry, I didn't play that much with MQTT so I don't know.

Can I close this issue?

**Comment by mikkelking** [comment]
Here is someone who has interfaced to MQTT, might be a good starting point

https://github.com/mkarliner/meteor-mqtt

Cheers

Mike

**Comment by yilunyu** [comment]
@perak yes please close this thread.
