### ISSUE TITLE
Compatible with meteor 1.3.4.1?

### ISSUE THREAD

**Issue by mttstt** [perak/kitchen-site#365]
Meterokitchen version used: 0.9.77

If I use the following commands  on Windows:  `meteor-kitchen ./Domoticasite.json ./Domoticasite` and `meteor --settings ../production-settings.json` then I haven't problems. 

But if I use the following command `meteor-kitchen ./Domoticasite.json ./Domoticasite --meteor-release 1.3.4.1` and then `meteor --settings ../production-settings.json  --release 1.3.4.1` I have this error:

```
W20170121-15:36:02.987(1)? (STDERR)
W20170121-15:36:03.035(1)? (STDERR) /home/pi/meteor/dev_bundle/server-lib/node_modules/fiber                                      s/future.js:280
W20170121-15:36:03.080(1)? (STDERR)                                             throw(ex);
W20170121-15:36:03.111(1)? (STDERR)                                                   ^
W20170121-15:36:36.537(1)? (STDERR) ReferenceError: SimpleSchema is not defined
W20170121-15:36:36.571(1)? (STDERR)     at meteorInstall.both.collections.caldaia.js (both/c                                      ollections/caldaia.js:17:28)
W20170121-15:36:36.621(1)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/packa                                      ge/node_modules/install/install.js:153:1)
W20170121-15:36:36.646(1)? (STDERR)     at require (packages/modules-runtime/.npm/package/no                                      de_modules/install/install.js:82:1)
W20170121-15:36:36.668(1)? (STDERR)     at /home/pi/Domoticasite/.meteor/local/build/program                                      s/server/app/app.js:1616:1
W20170121-15:36:36.685(1)? (STDERR)     at /home/pi/Domoticasite/.meteor/local/build/program                                      s/server/boot.js:297:10
W20170121-15:36:36.709(1)? (STDERR)     at Array.forEach (native)
W20170121-15:36:36.732(1)? (STDERR)     at Function._.each._.forEach (/home/pi/meteor/dev_bu                                      ndle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170121-15:36:36.754(1)? (STDERR)     at /home/pi/Domoticasite/.meteor/local/build/program                                      s/server/boot.js:133:5
=> Exited with code: 8
```

Any ideas? Thanks

**Comment by mttstt** [comment]
I point out that problem regards bcryp in "accounts-password".

**Comment by mttstt** [comment]
I don't know why, but I solved compilation problem with this trick:

1) cd C:\Users\xxx\AppData\Local\.meteor\packages\meteor-tool\1.3.4_1\mt-os.windows.x86_32\dev_bundle\bin

2) npm install node-gyp (NO -g)

**Comment by perak** [comment]
@mttstt thanks for sharing the solution 👍
