### ISSUE TITLE
Failed to run iOS app

### ISSUE THREAD

**Issue by The-Edge-Malaysia** [perak/kitchen-site#393]
Using meteor kitchen on Mac to generate a test app with -i switch.

When running with meteor run ios or meteor run ios-device it seems to have issue downloading Cordova plugins from the internet, and the app subsequently failed to run with error.

Even if I update meteor to 1.5.2, the same persist.

Anyone can help?

**Comment by The-Edge-Malaysia** [comment]
the following is the error log from running meteor run ios

=> Started proxy.                             
WARNING: Attempting to install plugin cordova-plugin-inappbrowser@1.6.1, but it
         should have a minimum version of 1.7.1 to ensure compatibility with
         the current platform versions. Installing the minimum version for
         convenience, but you should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-statusbar@2.2.1, but it
         should have a minimum version of 2.2.3 to ensure compatibility with
         the current platform versions. Installing the minimum version for
         convenience, but you should adjust your dependencies.
WARNING: Attempting to install plugin cordova-plugin-splashscreen@4.0.1, but it
         should have a minimum version of 4.0.3 to ensure compatibility with
         the current platform versions. Installing the minimum version for
         convenience, but you should adjust your dependencies.
=> Started MongoDB.                                                             
%% Failed to install 'cordova-plugin-googleplus': Error: Variable(s) missing: REVERSED_CLIENT_ID
    at /Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:334:23
    at _fulfilled (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
    at /Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:557:44
    at flush (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)
=> Errors executing Cordova commands:                                           
                                                                                
   While adding plugin                                                          
   https://github.com/meteor/cordova-plugin-googleplus.git#3095abe327e710ab04059ae9d3521bd4037c5a37
   to Cordova project:
   Error: Variable(s) missing: REVERSED_CLIENT_ID                               
   at
   /Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova-lib/src/plugman/install.js:334:23
   at _fulfilled
   (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:787:54)
   at self.promiseDispatch.done
   (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:816:30)
   at Promise.promise.promiseDispatch
   (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:749:13)
   at
   /Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:557:44
   at flush
   (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/q/q.js:108:17)
   at nextTickCallbackWith0Args (node.js:489:9)
   at process._tickCallback (node.js:418:13)
   => awaited here:
   at Function.Promise.await
   (/Users/chiacy/.meteor/packages/less/.2.7.9.1fjsu30++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:35:12)
   at CordovaProject.runCommands (/tools/cordova/project.js:715:22)
   at CordovaProject.addPlugin (/tools/cordova/project.js:509:12)
   at /tools/cordova/project.js:638:16
   at Function._.each._.forEach
   (/Users/chiacy/.meteor/packages/meteor-tool/.1.5.2_2.1899z8d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
   at /tools/cordova/project.js:637:11
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at CordovaProject.ensurePluginsAreSynchronized
   (/tools/cordova/project.js:535:18)
   at CordovaProject.prepareFromAppBundle
   (/tools/cordova/project.js:199:10)
   at /tools/cordova/runner.js:78:27
   at /tools/utils/buildmessage.js:359:18
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:352:34
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:350:23
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at Object.enterJob (/tools/utils/buildmessage.js:324:26)
   at CordovaRunner.prepareProject (/tools/cordova/runner.js:77:18)
   at /tools/runners/run-app.js:674:25
   at /tools/utils/buildmessage.js:271:13
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:264:29
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:262:18
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at /tools/utils/buildmessage.js:253:23
   at [object Object]._.extend.withValue
   (/tools/utils/fiber-helpers.js:89:14)
   at Object.capture (/tools/utils/buildmessage.js:252:19)
   at [object Object]._.extend._runOnce (/tools/runners/run-app.js:673:39)
   at [object Object]._.extend._fiber (/tools/runners/run-app.js:885:28)
   at /tools/runners/run-app.js:412:12
                                                                                
/Users/chiacy/.meteor/packages/less/.2.7.9.1fjsu30++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
ExitWithCode:1

**Comment by The-Edge-Malaysia** [comment]
and when running meteor run iOS, 

 Installing Cordova plugins                [===                    ] 14% 91.1s

always at 14%

it works properly if code is not generated from meteor kitchen

**Comment by The-Edge-Malaysia** [comment]
the above happened when the following packages was added

accounts-base          added, version 1.3.4   
accounts-google        added, version 1.2.0
accounts-oauth         added, version 1.1.15
accounts-password      added, version 1.4.1
ddp-rate-limiter       added, version 1.0.7
google-oauth           added, version 1.2.4
localstorage           added, version 1.1.1
npm-bcrypt             added, version 0.9.3
oauth                  added, version 1.1.13
oauth2                 added, version 1.1.11
perak:user-roles       added, version 1.0.12
rate-limit             added, version 1.0.8
service-configuration  added, version 1.0.11
sha                    added, version 1.0.9
srp                    added, version 1.0.10
